base:
  install_dir: /opt
  mode: stable
  is_demo: false
  is_offline: false
  is_fxplay: false
  port: 9999
  username: admin
  password: admin123
  version: v2.1.5

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel-Core
  log_suffix: .log
  max_backup: 10
